controllers:
    resource: ../src/User/Application/Controller
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

user_index:
    path: /users
    controller: App\User\Application\Controller\UserController::index
    methods: GET